### ISSUE TITLE
[TRACKING] Tag Falco rules according to rules maturity framework and compliance use case if applicable

### ISSUE THREAD

**Issue by incertum** [falcosecurity/rules#101]
This issue will serve as a tracker for the implementation of the initial "Rules Maturity Framework" for Falco 0.36, as outlined in the proposal found at https://github.com/falcosecurity/rules/blob/main/proposals/20230605-rules-adoption-management-maturity-framework.md.

The proposed approach involves iterative tagging to make the process less complex, more structured, and auditable. While it may initially appear redundant and involve some back and forth in some cases, I believe it will allow us to be more deliberate in discussing and determining the appropriate level for each rule.

Categorizing the maturity of each rule:

Phase 1:
- [x] Tag each rule that is currently disabled by default with `maturity_sandbox`, without any exceptions.

Phase 2:
- [x] Re-audit the first round of rules tagged with `maturity_sandbox` and consider transitioning some to `maturity_incubating`, with a maximum of 5 rules per PR to enable focused discussions.
- [x] Directly tag a set of max 20 rules with `maturity_stable` that have already been established and proven useful in production settings. Each PR should focus on a maximum of 5 rules to facilitate discussions. All these rules must be enabled by default and contain a useful description, tuning guidance, and reflect best rule-writing practices. Refer to https://github.com/falcosecurity/rules/blob/main/proposals/20230605-rules-adoption-management-maturity-framework.md#rules-maturity-framework and https://github.com/falcosecurity/rules/blob/main/proposals/20230605-rules-adoption-management-maturity-framework.md#define-rule-contribution-process for more details.

Phase 3:
- [x] Categorize the remaining rules after completing the above steps and decide whether they best fit into `maturity_sandbox` or `maturity_incubating`.

Tagging rules with compliance-related tags:

- [x] Tag rules that help with PCI DSS compliance use cases, if applicable. Refer to https://falco.org/blog/falco-pci-controls/ for more information.
- [x] Tag rules according to NIST requirements, if applicable. Refer to https://falco.org/blog/falco-nist-controls/.

**Comment by incertum** [comment]
- [x] Enforce new Style Guide for output fields for each rule, see https://falco.org/docs/rules/style-guide/
