### ISSUE TITLE
[TRACKING] Phase 4 - Tag Falco rules according to rules maturity framework and compliance use case if applicable

### ISSUE THREAD

**Issue by incertum** [falcosecurity/rules#126]
**Motivation**

Create a new ticket to track Phase 4 from https://github.com/falcosecurity/rules/issues/101

Phase 4:
- [x] Once every rule has a maturity tag, re-audit and determine if some `maturity_incubating` rules should be graduated to `maturity_stable` after making necessary improvements. Similarly, assess `maturity_sandbox` rules for potential transition to `maturity_incubating`.
> - [x] Finally, disable all non `maturity_stable` rules by default, closer to the release of Falco 0.36, once the Falco binary has implemented improved configurability over `falco.yaml`.
^ above got deprecated based on new information that became available during the maintainers meeting on 2023

- [x] Once rules are re-balanced and we feel confident about the assignments, we will go ahead and split the rules according to the outlook provided in the [proposal](https://github.com/falcosecurity/rules/blob/main/proposals/20230605-rules-adoption-management-maturity-framework.md#rules-maturity-framework). 

```
falco_rules.yaml (keeping the old established file name for the stable rules)
falco_rules.incubating.yaml
falco_rules.sandbox.yaml
falco_rules.deprecated.yaml
```

Additional improvements

- [x] After tagging all rules, we will check if each rules' condition can be optimized wrt to robustness and noise.
- [x] Enhance desc for each rule

**Feature**

**Alternatives**

**Additional context**

**Comment by incertum** [comment]
@leogr for Phase 4 the following Falco updates are a prerequisite:

(1) https://github.com/falcosecurity/falco/pull/2671
(2) TBA fixing some issues with tags filtering and expanding unit tests and tests (started in (1)) 

in order to reliably support new rules loading mechanisms especially once we disable all non stable rules by default.

**Comment by incertum** [comment]
@leogr and @LucaGuerra kindly asking to confirm the changes I made above.

**Comment by leogr** [comment]
> @leogr re splitting the rules files, should we stage the new rules files and separate the respective rules out at the end after we have finished all the re-balancing etc? Or already split now? And do the additional changes afterwards?

I would like to preserve the git history, if possible. I would split rules files once we are confident that we won't move rules across maturity levels anymore. Any other additional changes can be done afterward. 

Currently, we have:
- 20 rules with _maturity_stable_
- 16 rules with _maturity_incubating_
- 44 rules with _maturity_sandbox_

Stable ones seem ok to me. I just see too many in the sandbox, but it could be just the reality.

By the way, I can split those files and preserve the git history. Let me know if we feel confident about the assignments, then I'll proceed. Please note that Luca is on vacation and won't reply soon.

**Comment by incertum** [comment]
@leogr this sounds like an excellent plan! Yes some sandbox rules shall move to incubating plus we still need to improve the `desc` throughout.

Let's target Sep 1, 2023 for having the rules "finalized" and then you can start with splitting them 👍 @leogr

**Comment by leogr** [comment]
> Let's target Sep 1, 2023 for having the rules "finalized" and then you can start with splitting them

This would be great! Then we have not to forget to give it a try in a Falco dev build or RC (as planned for the end of this iteration).

**Comment by incertum** [comment]
- [ ] See https://github.com/falcosecurity/rules/pull/140#issuecomment-1696005225, minor adjustments to the maturity framework needed.

**Comment by leogr** [comment]
Rules split done by https://github.com/falcosecurity/rules/pull/149

@incertum I think we can close this and proceed in _fine-tuning_ mode until the release.

**Comment by incertum** [comment]
Yes! Pending tasks fall under regular cleanup. Thanks for your help @leogr!
